name: lint

on:
  push:
    branches:
      - main
  pull_request:

env:
  UV_SYSTEM_PYTHON: true

permissions:
  contents: read

jobs:
  pre-commit-checks:
    name: Pre-commit checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup_python
        with:
          python-version: ${{ matrix.python-version }}

      - name: UV Cache
        uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv
          key: uvcache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements-client.txt', 'requirements.txt', 'requirements-dev.txt') }}

      - name: Install packages
        run: |
          python -m pip install -U uv pre-commit
          uv pip install --upgrade .

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
        env:
          SKIP: no-commit-to-branch
